package cli

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/fatih/color"
	"github.com/spf13/cobra"
)

func NewEnvCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "env",
		Short: "Manage development environment",
		Long: `Manage unified development environment with dev/prod parity:

- Setup development containers
- Validate environment health
- Clean development data
- Configure IDE integration`,
	}

	cmd.AddCommand(newEnvSetupCmd())
	cmd.AddCommand(newEnvStatusCmd())
	cmd.AddCommand(newEnvCleanCmd())

	return cmd
}

func newEnvSetupCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "setup",
		Short: "Setup development environment",
		Long:  "Sets up unified development environment with containers and services",
		RunE: func(cmd *cobra.Command, args []string) error {
			color.Blue("🏗️ Setting up development environment...")
			
			return setupEnvironment()
		},
	}
}

func newEnvStatusCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "status",
		Short: "Check environment health",
		Long:  "Validates development environment and service health",
		RunE: func(cmd *cobra.Command, args []string) error {
			color.Blue("🔍 Checking environment status...")
			
			return checkEnvironmentStatus()
		},
	}
}

func newEnvCleanCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "clean",
		Short: "Clean development data",
		Long:  "Cleans development databases, caches, and temporary data",
		RunE: func(cmd *cobra.Command, args []string) error {
			color.Blue("🧹 Cleaning development environment...")
			
			return cleanEnvironment()
		},
	}
}

func setupEnvironment() error {
	// Check if we're in a project directory
	if _, err := os.Stat(".git"); os.IsNotExist(err) {
		color.Yellow("⚠️  Not in a git repository. Consider running 'git init' first.")
	}

	// Check for common development tools
	tools := []struct {
		name    string
		command string
		install string
	}{
		{"Git", "git", "Install from https://git-scm.com/"},
		{"Docker", "docker", "Install from https://docker.com/"},
		{"Node.js", "node", "Install from https://nodejs.org/"},
		{"Go", "go", "Install from https://golang.org/"},
	}

	color.Green("✅ Checking development tools...")
	for _, tool := range tools {
		if _, err := exec.LookPath(tool.command); err != nil {
			color.Yellow("⚠️  %s not found. %s", tool.name, tool.install)
		} else {
			color.Green("✓ %s found", tool.name)
		}
	}

	// Create common development directories
	dirs := []string{".codekeeper", ".codekeeper/config", ".codekeeper/logs"}
	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("failed to create directory %s: %w", dir, err)
		}
	}
	color.Green("✓ Created .codekeeper directory structure")

	// Create development environment file
	envFile := `.codekeeper/env.local
# CodeKeeper Development Environment
# This file is automatically generated and can be customized

# Development mode settings
CODEKEEPER_ENV=development
CODEKEEPER_LOG_LEVEL=debug

# AI Assistant settings
CODEKEEPER_GUARD_RAILS_STRICT=false
CODEKEEPER_COMPLIANCE_CHECK=true

# Domain settings (auto-detected or override)
CODEKEEPER_DOMAIN=auto

# MCP server settings
CODEKEEPER_MCP_PORT=3000
CODEKEEPER_MCP_HOST=localhost
`

	if err := os.WriteFile(".codekeeper/env.local", []byte(envFile), 0644); err != nil {
		return fmt.Errorf("failed to create env.local: %w", err)
	}
	color.Green("✓ Created environment configuration")

	// Create .gitignore entry for CodeKeeper
	gitignoreEntry := `
# CodeKeeper
.codekeeper/logs/
.codekeeper/cache/
.codekeeper/*.tmp
`
	if err := appendToGitignore(gitignoreEntry); err != nil {
		color.Yellow("⚠️  Could not update .gitignore: %v", err)
	} else {
		color.Green("✓ Updated .gitignore")
	}

	color.Green("🎉 Development environment setup complete!")
	fmt.Println()
	color.Blue("📋 Next steps:")
	fmt.Println("  1. codekeeper env status  - Check environment health")
	fmt.Println("  2. codekeeper cursor setup - Setup Cursor IDE integration")
	fmt.Println("  3. codekeeper check - Run guard rails validation")

	return nil
}

func checkEnvironmentStatus() error {
	checks := []struct {
		name string
		fn   func() (bool, string)
	}{
		{"Git repository", checkGitRepo},
		{"CodeKeeper config", checkCodeKeeperConfig},
		{"Environment file", checkEnvFile},
		{"Docker available", checkDocker},
		{"Cursor config", checkCursorConfig},
	}

	allPassed := true
	for _, check := range checks {
		passed, message := check.fn()
		if passed {
			color.Green("✓ %s", check.name)
		} else {
			color.Red("✗ %s: %s", check.name, message)
			allPassed = false
		}
	}

	fmt.Println()
	if allPassed {
		color.Green("🎉 Environment is healthy!")
	} else {
		color.Yellow("⚠️  Some issues found. Run 'codekeeper env setup' to fix.")
		return fmt.Errorf("environment issues detected")
	}

	return nil
}

func cleanEnvironment() error {
	// Clean temporary files
	patterns := []string{
		".codekeeper/logs/*",
		".codekeeper/cache/*",
		".codekeeper/*.tmp",
		"*.log",
	}

	cleaned := 0
	for _, pattern := range patterns {
		matches, err := filepath.Glob(pattern)
		if err != nil {
			continue
		}
		for _, match := range matches {
			if err := os.RemoveAll(match); err == nil {
				cleaned++
			}
		}
	}

	color.Green("✓ Cleaned %d temporary files", cleaned)

	// Clean Docker if available
	if _, err := exec.LookPath("docker"); err == nil {
		color.Blue("🐳 Cleaning Docker resources...")
		exec.Command("docker", "system", "prune", "-f").Run()
		color.Green("✓ Docker cleanup complete")
	}

	color.Green("🎉 Environment cleanup complete!")
	return nil
}

func checkGitRepo() (bool, string) {
	if _, err := os.Stat(".git"); os.IsNotExist(err) {
		return false, "not in a git repository"
	}
	return true, ""
}

func checkCodeKeeperConfig() (bool, string) {
	if _, err := os.Stat(".codekeeper"); os.IsNotExist(err) {
		return false, "run 'codekeeper env setup' first"
	}
	return true, ""
}

func checkEnvFile() (bool, string) {
	if _, err := os.Stat(".codekeeper/env.local"); os.IsNotExist(err) {
		return false, "environment file missing"
	}
	return true, ""
}

func checkDocker() (bool, string) {
	if _, err := exec.LookPath("docker"); err != nil {
		return false, "Docker not installed"
	}
	cmd := exec.Command("docker", "info")
	if err := cmd.Run(); err != nil {
		return false, "Docker not running"
	}
	return true, ""
}

func checkCursorConfig() (bool, string) {
	cursorSettings := filepath.Join(os.Getenv("HOME"), ".cursor", "settings.json")
	if _, err := os.Stat(cursorSettings); os.IsNotExist(err) {
		return false, "Cursor not configured"
	}
	return true, ""
}

func appendToGitignore(content string) error {
	// Check if .gitignore exists
	gitignorePath := ".gitignore"
	var existingContent []byte
	var err error

	if _, err := os.Stat(gitignorePath); err == nil {
		existingContent, err = os.ReadFile(gitignorePath)
		if err != nil {
			return err
		}
	}

	// Check if content already exists
	if strings.Contains(string(existingContent), "# CodeKeeper") {
		return nil // Already added
	}

	// Append content
	file, err := os.OpenFile(gitignorePath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer file.Close()

	_, err = file.WriteString(content)
	return err
}