package tooling

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// GitGenerator handles Git repository initialization and configuration
type GitGenerator struct {
	spec *ProjectSpec
}

// ProjectSpec represents the project specification (imported from parent package)
type ProjectSpec struct {
	Name        string
	Description string
	Domain      string
	CoreEntity  string
	Backend     string
	ProjectPath string
}

// NewGitGenerator creates a new Git generator
func NewGitGenerator(spec *ProjectSpec) *GitGenerator {
	return &GitGenerator{spec: spec}
}

// Generate initializes git repository and creates git-related files
func (gg *GitGenerator) Generate() error {
	if err := gg.initializeGitRepository(); err != nil {
		return err
	}
	
	if err := gg.generateGitAttributes(); err != nil {
		return err
	}
	
	return nil
}

// initializeGitRepository sets up the git repository with initial commit
func (gg *GitGenerator) initializeGitRepository() error {
	// Check if git is available
	if _, err := exec.LookPath("git"); err != nil {
		fmt.Printf("⚠️  Git not found, skipping repository initialization\n")
		return nil
	}

	// Check if already a git repository
	gitDir := filepath.Join(gg.spec.ProjectPath, ".git")
	if _, err := os.Stat(gitDir); err == nil {
		fmt.Printf("📁 Git repository already exists, skipping initialization\n")
		return nil
	}

	// Initialize git repository
	cmd := exec.Command("git", "init")
	cmd.Dir = gg.spec.ProjectPath
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("failed to initialize git repository: %w", err)
	}

	// Create .gitignore file
	gitignoreContent := gg.generateGitignore()
	gitignorePath := filepath.Join(gg.spec.ProjectPath, ".gitignore")
	if err := os.WriteFile(gitignorePath, []byte(gitignoreContent), 0644); err != nil {
		return fmt.Errorf("failed to create .gitignore: %w", err)
	}

	// Add all files
	cmd = exec.Command("git", "add", ".")
	cmd.Dir = gg.spec.ProjectPath
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("failed to add files to git: %w", err)
	}

	// Create initial commit
	commitMessage := fmt.Sprintf("Initial commit: %s\n\nGenerated with AI CodeKeeper v2.0.0\nDomain: %s\nCore Entity: %s", 
		gg.spec.Name, gg.spec.Domain, gg.spec.CoreEntity)
	
	cmd = exec.Command("git", "commit", "-m", commitMessage)
	cmd.Dir = gg.spec.ProjectPath
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("failed to create initial commit: %w", err)
	}

	fmt.Printf("✅ Git repository initialized with initial commit\n")
	return nil
}

// generateGitignore creates a comprehensive .gitignore file
func (gg *GitGenerator) generateGitignore() string {
	gitignore := `# Dependencies
node_modules/
*.pnp
.pnp.js

# Testing
/coverage/
*.lcov

# Production builds
/build/
/dist/
/.next/
/out/

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage/
*.lcov

# nyc test coverage
.nyc_output

# Dependency directories
node_modules/
jspm_packages/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# next.js build output
.next
out

# nuxt.js build output
.nuxt

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
pip-wheel-metadata/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# PyInstaller
*.manifest
*.spec

# Installer logs
pip-log.txt
pip-delete-this-directory.txt

# Unit test / coverage reports
htmlcov/
.tox/
.nox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
*.py,cover
.hypothesis/
.pytest_cache/

# Translations
*.mo
*.pot

# Django stuff:
*.log
local_settings.py
db.sqlite3
db.sqlite3-journal

# Flask stuff:
instance/
.webassets-cache

# Scrapy stuff:
.scrapy

# Sphinx documentation
docs/_build/

# PyBuilder
target/

# Jupyter Notebook
.ipynb_checkpoints

# IPython
profile_default/
ipython_config.py

# pyenv
.python-version

# pipenv
Pipfile.lock

# PEP 582
__pypackages__/

# Celery stuff
celerybeat-schedule
celerybeat.pid

# SageMath parsed files
*.sage.py

# Environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

# Spyder project settings
.spyderproject
.spyproject

# Rope project settings
.ropeproject

# mkdocs documentation
/site

# mypy
.mypy_cache/
.dmypy.json
dmypy.json

# Pyre type checker
.pyre/

# Go
# Binaries for programs and plugins
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary, built with "go test -c"
*.test

# Output of the go build
main

# Dependency directories (remove the comment below to include it)
vendor/

# Go workspace file
go.work

# IDE
.idea/
.vscode/
*.swp
*.swo
*~

# OS
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db

# Docker
.dockerignore

# Terraform
*.tfstate
*.tfstate.*
.terraform/
.terraform.lock.hcl

# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Coverage directory used by tools like istanbul
coverage/
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Next.js build output
.next

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
public

# Storybook build outputs
.out
.storybook-out

# Temporary folders
tmp/
temp/

# Editor directories and files
.vscode/*
!.vscode/extensions.json
!.vscode/settings.json
!.vscode/launch.json
.idea
.DS_Store
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?

# CodeKeeper specific
.codekeeper/env.local
.codekeeper/cache/
`

	return gitignore
}

// generateGitAttributes creates .gitattributes file for consistent line endings
func (gg *GitGenerator) generateGitAttributes() error {
	content := `# Git attributes for consistent line endings and file handling

# Auto detect text files and perform LF normalization
* text=auto

# Explicitly declare text files you want to always be normalized
*.md text
*.js text
*.ts text
*.tsx text
*.json text
*.yaml text
*.yml text
*.css text
*.html text
*.sql text

# Declare files that will always have CRLF line endings on checkout
*.bat text eol=crlf

# Denote all files that are truly binary and should not be modified
*.png binary
*.jpg binary
*.jpeg binary
*.gif binary
*.ico binary
*.mov binary
*.mp4 binary
*.mp3 binary
*.flv binary
*.fla binary
*.swf binary
*.gz binary
*.zip binary
*.7z binary
*.ttf binary
*.eot binary
*.woff binary
*.woff2 binary
*.pyc binary
*.pdf binary
*.ez binary
*.bz2 binary
*.swp binary
*.lz binary

# Docker files
Dockerfile* text
*.dockerignore text

# Git files
.gitignore text
.gitattributes text

# CI/CD files
.github/** text

# Terraform files
*.tf text
*.tfvars text
*.hcl text`

	filePath := filepath.Join(gg.spec.ProjectPath, ".gitattributes")
	return os.WriteFile(filePath, []byte(content), 0644)
}

// GetBackendLanguage extracts the programming language from backend choice
func (spec *ProjectSpec) GetBackendLanguage() string {
	switch {
	case strings.Contains(strings.ToLower(spec.Backend), "node"):
		return "javascript"
	case strings.Contains(strings.ToLower(spec.Backend), "python"):
		return "python"
	case strings.Contains(strings.ToLower(spec.Backend), "go"):
		return "go"
	default:
		return "javascript" // Default fallback
	}
}